// <auto-generated />
using System;
using ISW2_Primer_parcial.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISW2_Primer_parcial.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ISW2_Primer_parcial.Models.Inventario", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaFechaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("IdProducto");

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("ISW2_Primer_parcial.Models.MovimientosInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProducto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipoMovimiento")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaFechaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdTipoMovimiento");

                    b.ToTable("MovimientosInventario", (string)null);
                });

            modelBuilder.Entity("ISW2_Primer_parcial.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimoExistencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UltimaFechaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("IdProducto");

                    b.HasIndex("CodigoProducto")
                        .IsUnique();

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("ISW2_Primer_parcial.Models.TipoMovimiento", b =>
                {
                    b.Property<int>("IdTipoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTipoMovimiento");

                    b.ToTable("TipoMovimiento", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoMovimiento = 1,
                            Tipo = "Entrada"
                        },
                        new
                        {
                            IdTipoMovimiento = 2,
                            Tipo = "Salida"
                        });
                });

            modelBuilder.Entity("ISW2_Primer_parcial.Models.Inventario", b =>
                {
                    b.HasOne("ISW2_Primer_parcial.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ISW2_Primer_parcial.Models.MovimientosInventario", b =>
                {
                    b.HasOne("ISW2_Primer_parcial.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISW2_Primer_parcial.Models.TipoMovimiento", "TipoMovimiento")
                        .WithMany()
                        .HasForeignKey("IdTipoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("TipoMovimiento");
                });
#pragma warning restore 612, 618
        }
    }
}
